USE HRDB;

DROP TABLE TBL_STG_EMPLOYEES;
CREATE TABLE TBL_STG_EMPLOYEES
(EMPLOYEE_ID INT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),	
EMAIL VARCHAR(20),
PHONE_NUMBER VARCHAR(13),	
HIRE_DATE DATE,	
JOB_ID VARCHAR(10),
SALARY DECIMAL(10,2),
COMMISSION_PCT DECIMAL(3,2),
MANAGER_ID INT,
DEPARTMENT_ID INT
);

SELECT * FROM TBL_STG_EMPLOYEES;

DROP TABLE TBL_STG_JOBS;
CREATE TABLE TBL_STG_JOBS
(JOB_ID VARCHAR(10),	
JOB_TITLE VARCHAR(45),
MIN_SALARY INT,
MAX_SALARY INT
);

DROP TABLE TBL_STG_DEPARTMENTS;
CREATE TABLE TBL_STG_DEPARTMENTS
(DEPARTMENT_ID INT,
DEPARTMENT_NAME	VARCHAR(50),
MANAGER_ID INT,
LOCATION_ID INT
);
SELECT * FROM TBL_STG_DEPARTMENTS;


DROP TABLE TBL_STG_COUNTRIES;
CREATE TABLE TBL_STG_COUNTRIES
(COUNTRY_ID	VARCHAR(2),
COUNTRY_NAME VARCHAR(50),
REGION_ID INT
);
SELECT * FROM TBL_STG_COUNTRIES;

DROP TABLE TBL_STG_LOCATIONS;
CREATE TABLE TBL_STG_LOCATIONS
(LOCATION_ID INT,	
STREET_ADDRESS VARCHAR(50),
POSTAL_CODE	VARCHAR(5),
CITY VARCHAR(25), 	
STATE_PROVINCE VARCHAR(25),	
COUNTRY_ID VARCHAR(2)
);

SELECT * FROM TBL_STG_LOCATIONS;

DROP TABLE TBL_STG_REGIONS;
CREATE TABLE TBL_STG_REGIONS
(REGION_ID INT,
REGION_NAME VARCHAR(22)
);

SELECT * FROM TBL_STG_REGIONS;

DROP TABLE TBL_STG_JOB_HISTORY;
CREATE TABLE TBL_STG_JOB_HISTORY
(EMPLOYEE_ID INT,
START_DATE DATE,
END_DATE DATE,	
JOB_ID VARCHAR(10),
DEPARTMENT_ID INT
);
SELECT * FROM TBL_STG_JOB_HISTORY;